-- Crivus QuizIQ Database Schema
-- Execute this SQL in your Supabase PostgreSQL database

-- Create enums
CREATE TYPE IF NOT EXISTS role AS ENUM ('super_admin', 'friend');
CREATE TYPE IF NOT EXISTS member_role AS ENUM ('viewer');

-- Users
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  pass_hash TEXT NOT NULL,
  role role NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_login_at TIMESTAMPTZ
);

-- Invites
CREATE TABLE IF NOT EXISTS invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT UNIQUE NOT NULL,
  email TEXT NOT NULL,
  role role NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  one_time BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Trackers
CREATE TABLE IF NOT EXISTS trackers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tracker_id TEXT UNIQUE NOT NULL,
  owner_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  site_url TEXT NOT NULL,
  origins TEXT[] NOT NULL DEFAULT '{}',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  page_rules JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked_at TIMESTAMPTZ
);

-- Tracker Members (sharing)
CREATE TABLE IF NOT EXISTS tracker_members (
  tracker_id TEXT NOT NULL REFERENCES trackers(tracker_id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role member_role NOT NULL DEFAULT 'viewer',
  PRIMARY KEY (tracker_id, user_id)
);

-- Events
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts BIGINT NOT NULL,
  ev TEXT NOT NULL,
  sid TEXT NOT NULL,
  tracker_id TEXT NOT NULL REFERENCES trackers(tracker_id) ON DELETE CASCADE,
  page_url TEXT NOT NULL,
  path TEXT NOT NULL,
  ref TEXT,
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  utm_term TEXT,
  utm_content TEXT,
  sw INT,
  sh INT,
  quiz_id TEXT,
  question_id TEXT,
  answer_id TEXT,
  extra JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for events
CREATE INDEX IF NOT EXISTS idx_events_tracker_ts ON events(tracker_id, ts);
CREATE INDEX IF NOT EXISTS idx_events_tracker_path ON events(tracker_id, path);

-- Leads
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts BIGINT NOT NULL,
  tracker_id TEXT NOT NULL REFERENCES trackers(tracker_id) ON DELETE CASCADE,
  sid TEXT NOT NULL,
  email TEXT,
  name TEXT,
  phone TEXT,
  extra JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for leads
CREATE INDEX IF NOT EXISTS idx_leads_tracker_ts ON leads(tracker_id, ts);

-- Policies (global settings)
CREATE TABLE IF NOT EXISTS policies (
  id BOOLEAN PRIMARY KEY DEFAULT TRUE,
  max_trackers_per_user INT NOT NULL DEFAULT 10,
  max_collect_rps_per_origin INT NOT NULL DEFAULT 10,
  retention_days INT NOT NULL DEFAULT 365,
  allowed_origins TEXT[] NOT NULL DEFAULT '{}'
);

-- Insert default policies
INSERT INTO policies (id, max_trackers_per_user, max_collect_rps_per_origin, retention_days, allowed_origins)
VALUES (true, 10, 10, 365, '{}')
ON CONFLICT (id) DO NOTHING;

-- Auth Attempts (for lockout)
CREATE TABLE IF NOT EXISTS auth_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT,
  ip INET,
  success BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for auth attempts
CREATE INDEX IF NOT EXISTS idx_auth_attempts_email_created ON auth_attempts(email, created_at);
CREATE INDEX IF NOT EXISTS idx_auth_attempts_ip_created ON auth_attempts(ip, created_at);

